# Check out https://docs.codemagic.io/yaml/building-a-native-android-app/ for more information

workflows:
  android-app:
    name: My VKU
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk